### ISSUE TITLE
Type3 docs v1.0

### ISSUE THREAD

**Issue by emolinaro** [SDU-eScience/Type3-Docs#1]
- [x] Create template with Sphinx 
- [x] Add preliminary TOC
- [x] Add SSH login description
- [x] Add modules description
- [x] Add compilers description
- [x] Add section about new software
- [x] Create script for Docker image and deployment
